### ISSUE TITLE
Please provide the windows 64bit executable 

### ISSUE THREAD

**Issue by shaiful73** [mullvad/win-split-tunnel#41]
I was trying to build last 7 days. please help me

**Comment by faern** [comment]
Hi! I'm not sure what your goal is, but you can find our compiled and signed `win-split-tunnel` drivers here:
* x86 https://github.com/mullvad/mullvadvpn-app-binaries/tree/main/x86_64-pc-windows-msvc/split-tunnel
* ARM64 https://github.com/mullvad/mullvadvpn-app-binaries/tree/main/aarch64-pc-windows-msvc/split-tunnel

What is it you need them for, if I may ask? Maybe we can help better if we understand the use case.

**Comment by faern** [comment]
Ok! The links I provided are the versions we use in our app. Good luck with your software! I will close this now since we have resolved the question.
